### ISSUE TITLE
Error failed to fetch an image or build from source

### ISSUE THREAD

**Issue by abgregs** [Girish21/speed-metal-stack#16]
Not sure if others are experiencing this issue, but I just recently started with this stack (great work and thank you for making it 😄 ) and I had to troubleshoot the below error that was causing my deploy to fail.

```
==> Verifying app config
--> Verified app config
==> Building image
Searching for image 'registry.fly.io/***:[...] locally...
Searching for image 'registry.fly.io/***:[...] remotely...
Error failed to fetch an image or build from source: Could not find image "registry.fly.io/***:[...]
```

Of course now I can't find the discussion link where I found the solution but this is what got it working for me.

In `deploy.yml` changed:

```
 - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
```
to: 

```
 - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1
```

The main thing was specifying the version. Hopefully this helps if others are also running into the issue. Not sure if it's just me or the issue should be resolved another way, but if it'd be helpful I can add a PR.
